"use client";

import { useState } from "react";
import { Drawer } from "@mui/material";
import { config } from "@/config";
import ModelConfig from "./sidebar/ModelConfig";
import PromptEditor from "./sidebar/PromptEditor";
import GenerateButton from "./sidebar/GenerateButton";
import CostBreakdownPanel, { CostBreakdown } from "./sidebar/CostBreakdownPanel";
import FileDropzone, { AttachedFile } from "./sidebar/FileDropzone";
import AdvancedConfig from "./sidebar/AdvancedConfig";

interface SidebarLeftProps {
  open: boolean;
  token: string;
  onGenerate: (xml: string) => void;
}

export default function SidebarLeft({
  open,
  token,
  onGenerate,
}: SidebarLeftProps) {
  const drawerWidth = config.ui.sidebarWidth;
  const [prompt, setPrompt] = useState("Create a simple flowchart with 3 steps.");
  const [systemInstructions, setSystemInstructions] = useState("");
  const [model, setModel] = useState(config.gemini.defaultModel);
  const [thinkingLevel, setThinkingLevel] = useState("medium");
  const [requestTier, setRequestTier] = useState("standard");
  const [loading, setLoading] = useState(false);
  const [costBreakdown, setCostBreakdown] = useState<CostBreakdown | null>(null);
  const [attachments, setAttachments] = useState<AttachedFile[]>([]);

  const handleGenerate = async () => {
    setLoading(true);
    try {
      const endpoint = config.gemini.endpointPattern
        .replace(/\[REGION\]/g, config.google.region)
        .replace(/\[PROJECT_ID\]/g, config.google.projectId)
        .replace(/\[MODEL\]/g, encodeURIComponent(model));

      const requestParts: any[] = [];
      let finalPromptText = prompt;

      attachments.forEach((att) => {
        if (att.type.startsWith("image/")) {
          requestParts.push({
            inlineData: {
              mimeType: att.type,
              data: att.data.split(",")[1],
            },
          });
        } else {
          finalPromptText += `\n\n--- Content of attached file: ${att.name} ---\n${att.data}\n--- End of file ---\n`;
        }
      });

      requestParts.push({ text: finalPromptText });

      const headers: Record<string, string> = {
        "Content-Type": "application/json",
      };

      // Only add Authorization header if not using IAP
      // When using IAP, the proxy handles authentication, but Vertex AI still needs a token
      // However, if we're in IAP mode, we might expect the token to be different or omitted 
      // if relying on service account impersonation or similar, but usually we still need 
      // the Bearer token for the API. 
      // If the user meant "bypass our own auth storage", we should check how the token is passed.
      if (!config.google.iap.enabled || token !== 'iap-authorized') {
        headers.Authorization = `Bearer ${token}`;
      }

      if (requestTier === "flex") {
        headers["X-Vertex-AI-LLM-Request-Type"] = "shared";
        headers["X-Vertex-AI-LLM-Shared-Request-Type"] = "flex";
      } else if (requestTier === "priority") {
        headers["X-Vertex-AI-LLM-Request-Type"] = "shared";
        headers["X-Vertex-AI-LLM-Shared-Request-Type"] = "priority";
      }

      const response = await fetch(endpoint, {
        method: "POST",
        headers,
        body: JSON.stringify({
          contents: [{ role: "user", parts: requestParts }],
          systemInstruction: { parts: [{ text: systemInstructions }] },
          generationConfig: {
            temperature: 0.2,
          },
        }),
      });

      if (response.status === 401 || response.status === 403) {
        console.warn("Auth token is invalid or expired. Forcing re-login.");
        localStorage.removeItem("google_access_token");
        localStorage.removeItem("google_access_token_expires");
        window.location.reload();
        return;
      }

      if (!response.ok) {
        console.warn("Vertex AI call failed. Using fallback XML stub.");
        onGenerate(
          `<mxGraphModel><root><mxCell id="0"/><mxCell id="1" parent="0"/><mxCell id="2" value="Generated by Gemini" vertex="1" parent="1"><mxGeometry x="100" y="100" width="120" height="60" as="geometry"/></mxCell></root></mxGraphModel>`,
        );
        return;
      }

      const data = await response.json();

      const usage = data.usageMetadata;
      if (usage) {
        const respModelVersion = data.modelVersion || model;
        const matchedModel =
          config.gemini.models.find((m) => respModelVersion.includes(m.id)) ||
          config.gemini.models.find((m) => m.id === model);

        const pricingTier = requestTier === "priority" ? "priority" : "standard";
        const pricing = (matchedModel?.pricing as any)?.[pricingTier] || { input: 0, output: 0 };

        const inputTokens = usage.promptTokenCount || 0;
        const plainOutputTokens = usage.candidatesTokenCount || 0;
        const reasoningTokens =
          usage.thoughtsTokenCount ||
          usage.candidatesTokenDetails?.reasoningTokens ||
          usage.candidatesTokenDetails?.reasoningTokenCount ||
          0;

        const inputCost = (inputTokens / 1_000_000) * pricing.input;
        const reasoningCost = (reasoningTokens / 1_000_000) * pricing.output;
        const plainOutputCost = (plainOutputTokens / 1_000_000) * pricing.output;
        const totalOutputTokens = plainOutputTokens + reasoningTokens;
        const totalOutputCost = plainOutputCost + reasoningCost;

        const multiplier = requestTier === "flex" ? 0.5 : 1;

        setCostBreakdown({
          inputTokens,
          plainOutputTokens,
          reasoningTokens,
          totalOutputTokens,
          inputCost: inputCost * multiplier,
          plainOutputCost: plainOutputCost * multiplier,
          reasoningCost: reasoningCost * multiplier,
          totalOutputCost: totalOutputCost * multiplier,
          total: (inputCost + totalOutputCost) * multiplier,
        });
      }

      let generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text || "";

      if (generatedText.includes("```xml")) {
        generatedText = generatedText.split("```xml")[1].split("```")[0].trim();
      } else if (generatedText.includes("<mxGraphModel")) {
        generatedText = generatedText.substring(
          generatedText.indexOf("<mxGraphModel"),
        );
      }

      onGenerate(generatedText);
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  return (
    <Drawer
      variant="persistent"
      anchor="left"
      open={open}
      sx={{
        width: open ? drawerWidth : 0,
        flexShrink: 0,
        "& .MuiDrawer-paper": {
          width: drawerWidth,
          boxSizing: "border-box",
          mt: "48px",
          p: 2,
          height: "calc(100vh - 48px)",
        },
      }}
    >
      <ModelConfig
        model={model}
        thinkingLevel={thinkingLevel}
        requestTier={requestTier}
        onModelChange={setModel}
        onThinkingLevelChange={setThinkingLevel}
        onRequestTierChange={setRequestTier}
      />

      <PromptEditor prompt={prompt} onPromptChange={setPrompt} />

      <GenerateButton loading={loading} onClick={handleGenerate} />

      {costBreakdown && (
        <CostBreakdownPanel
          data={costBreakdown}
          requestTier={requestTier}
          onClose={() => setCostBreakdown(null)}
        />
      )}

      <FileDropzone
        attachments={attachments}
        onAttachmentsChange={setAttachments}
      />

      <AdvancedConfig
        systemInstructions={systemInstructions}
        onSystemInstructionsChange={setSystemInstructions}
      />
    </Drawer>
  );
}
